version: '3'
services:

  frontend:
    build: ./
    container_name: my-angular-app
    ports:
      - '51008:4200'

  nodeserver:
    build: ./server/
    container_name: server
    ports:
      - '3000:3000'
    links:
      - database
    
  database:
    image: mongo:latest
    container_name: mongo-db-test
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017