version: '3'
services:
  frontend:
    build: ./
    container_name: my-angular-app
    ports:
      - '51008:80'
  database:
    image: mongo:latest
    container_name: mongo-db-test
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles
  backend:
    build: ./server/
    container_name: express-server
    ports:
      - '3000:3000'
    links:
      - database