version: '3'
services:

  frontend:
    build: ./
    container_name: my-angular-app
    ports:
      - '51008:80'
    networks: 
      - skynet

  nodeserver:
    build: ./server/
    container_name: server
    expose:
      - 3000
    ports:
      - '3000:3000'
    links:
      - database
    networks: 
      - skynet
    
  database:
    image: mongo:latest
    container_name: mongo-db-test
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks: 
      - skynet
  
networks:
  skynet: {}